### ISSUE TITLE
Make the dependency plugin as module

### ISSUE THREAD

**Issue by david-binda** [david-binda/community-translator#1]

**Comment by zaantar** [comment]
I assume it's this one: https://github.com/hewsut/gp-extended-api-plugins/tree/master/gp-translation-extended-api

Not sure how to add it as a (npm) module since it's in a subdirectory of a git repository (see https://github.com/npm/npm/issues/2974).

**Comment by david-binda** [comment]
I don't think this issue is still relevant.

In order to be able to use the community translator, you either need a standalone GlotPress installation with https://github.com/hewsut/gp-extended-api-plugins/tree/master/gp-translation-extended-api plugin installed or a GlotPress as a WordPress plugin installed with https://github.com/david-binda/gp-extended-api-plugins plugin installed and activated via WordPress.

There is a chance that the former will make it to GlotPress' core (we might want to check on that) and the later is as simple as installing a WordPress plugin.

Let's close this one as invalid.
