### ISSUE TITLE
Respect WordPress' naming conventions

### ISSUE THREAD

**Issue by david-binda** [david-binda/community-translator#4]
The W[ordPress PHP coding standards’ naming conventions](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions) say that no camelCase should be used in variable nor class names.

**Comment by zaantar** [comment]
I agree, fixing. 

How about CamelCase in namespaces?

**Comment by david-binda** [comment]
I'm actually not sure whether PHP allows to usage of dashes and/or underscores in namespaces, does it?

**Comment by zaantar** [comment]
It allows underscores (not dashes).

**Comment by david-binda** [comment]
underscores are meant for separating words in PHP per WordPress coding standards. So if that makes sense, let's use underscores just for the sake of consistency. But don't have a strong opinion on this. Your call @zaantar  :)
